  spring:
    application:
      name: WebRestService
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  server:
    port: 8777